paul999_profileguestbook_post_controller:
    pattern: /profileguestbook/post/{USER}
    defaults: { _controller: paul999.profileguestbook.controller:post }
    requirements:
        user:  \d+

paul999_profileguestbook_edit_controller:
    pattern: /profileguestbook/edit/{USER}/{POST}
    defaults: { _controller: paul999.profileguestbook.controller:edit }
    requirements:
        user:  \d+
        post:  \d+

paul999_profileguestbook_delete_controller:
    pattern: /profileguestbook/delete/{USER}/{POST}
    defaults: { _controller: paul999.profileguestbook.controller:delete }
    requirements:
        user:  \d+
        post:  \d+

paul999_profileguestbook_report_controller:
    pattern: /profileguestbook/report/{USER}/{POST}
    defaults: { _controller: paul999.profileguestbook.controller:report }
    requirements:
        user:  \d+
        post:  \d+

paul999_profileguestbook_info_controller:
    pattern: /profileguestbook/info/{USER}/{POST}
    defaults: { _controller: paul999.profileguestbook.controller:info }
    requirements:
        user:  \d+
        post:  \d+
