imports:
    - { resource: tables.yml }
    
services:
    paul999.profileguestbook.listener:
        class: paul999\profileguestbook\event\profile_listener
        arguments:
            - @template
            - @user
            - @dbal.conn
            - %tables.profile_guestbook%
        tags:
            - { name: event.listener }

    paul999.profileguestbook.controller:
        class: paul999\profileguestbook\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @dbal.conn
            - %tables.profile_guestbook%
